name: Deploy to Server via SSH

on:
  push:
    branches:
      - dev
      - main
     
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy project via SSH 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/common/project/safesender
          docker system prune -a --force # temp solution
          make stop && make build && make start
